name: Lupus Decoupled Drupal Project
type: Lupus Decoupled Drupal
description: A recipe to setup a Lupus Decoupled Drupal project.
recipes:
  - drupal_cms_starter
  - lupus_decoupled_recipe_base
install:
  - services_env_parameter
