status: true
dependencies:
  config:
    - core.entity_view_mode.node.teaser
    - field.field.node.blog.field_featured_image
    - node.type.blog
id: node.blog.teaser
targetEntityType: node
bundle: blog
mode: teaser
useLayoutBuilder: false
forceAutoProcessing: false
customElementName: node-blog-teaser
content:
  featured_image:
    formatter: entity_ce_render
    field_name: field_featured_image
    is_slot: false
    weight: 0
    configuration:
      mode: 4_3_small
      flatten: 0
  path:
    formatter: auto
    field_name: path
    is_slot: false
    weight: 1
  title:
    formatter: auto
    field_name: title
    is_slot: false
    weight: -5
    configuration:
      settings:
        link_to_entity: 0
      third_party_settings: {  }
